let shirt = document.getElementById('shirt')
let tank = document.getElementById('tank')

function blackShirt() {
    shirt.setAttribute('src', 'Imagens/shirt-black.jpg')
}

function whiteShirt() {
    shirt.setAttribute('src', 'Imagens/shirt-white.webp')
}

function grayShirt() {
    shirt.setAttribute('src', 'Imagens/shirt-gray.jpg')
}

function blackTank() {
    tank.setAttribute('src', 'Imagens/regata-black.png')
}

function whiteTank() {
    tank.setAttribute('src', 'Imagens/regata-white.webp')
}

function grayTank() {
    tank.setAttribute('src', 'Imagens/regata-gray.png')
}